[package]
edition = "2021"
name = "bevy_veilid"
version = "0.0.1"
license = "Apache-2.0"
description = "Build turn-based p2p games with Veilid "
keywords = ["veilid", "bevy", "p2p", "turnbased"]
repository = "https://github.com/stillonearth/bevy_veilid"


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.11"
veilid_duplex = {path="../veilid_duplex"}
bevy-tokio-tasks = "0.11"