[package]
edition = "2021"
name = "bevy_veilid"
version = "0.1.2"
license = "Apache-2.0"
description = "Build turn-based p2p games with Veilid "
keywords = ["veilid", "bevy", "p2p", "turnbased"]
repository = "https://github.com/stillonearth/bevy_veilid"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.11"
veilid_duplex = "0.1.2"
bevy-tokio-tasks = "0.11"
serde = { version = "1.0.188", features= ["derive"] }
anyhow = "1.0.72"
copypasta = "0.10"
mini-redis = "0.4"

[dependencies.uuid]
version = "1.5.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dev-dependencies]
tracing-subscriber = { version = "0.3.17", features = [ "env-filter" ] }
tracing = "0.1.37"
belly = {git="https://github.com/jkb0o/belly", rev="ddd29fcd3e0b64a35f2290f3d0a1376ab1ebc8cf"}
